---
#-------------------------------
# General Site Settings

#title: Website
logo:
author: themefisher
description: this is meta description
email: randaadelnaguib@gmail.com
phone: +44 7979 005785
address: London, United Kingdom
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title-l1: Hi! I’m 
  # hero-title-l2: <br> Randa Naguib<br> 
  hero-title-l2: Randa Naguib
  hero-title-l3: Data Scientist

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: A result-driven data scientist with 4 years of experience in combining quantitative modeling and business understanding to deliver value-added insights. Demonstrated track record of working in a multi-cultural agile environment with a high tolerance for ambiguity. A master's degree holder in Data Science with a focus on Natural Language Processing from the University of Sussex.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Machine Learning, color: "#fdb157", value: "100%" }
  - { name: Data Analytics, color: "#9473e6", value: "90%" }
  - { name: Natural Language Processing, color: "#bdecf6", value: "80%" }
  - { name: Business Understanding, color: "#ffbcaa", value: "80%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Data Scientist,
      icon: "icon-3.png",
      date: "Jul 2023 - Present",
      organization: "Hastings Direct",
      location: "United Kingdom",
    }
  - {
      name: Data Scientist,
      icon: "icon-2.png",
      date: "Feb 2023 - Jul 2023",
      organization: "Jet Connectivity",
      location: "United Kingdom",
    }
  - {
      name: Data Scientist,
      icon: "icon-1.png",
      date: "Jul 2019 - Sep 2021",
      location: "Egypt",
      organization: "Etisalat Egypt",
    }
  

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Marters in Data Science, MSc,
      date: "Sep 2021 - Dec 2022",
      organization: "University of Sussex",
    }
  - {
      name: Bachelor of Engineering, Electronics and Communications Engineering,
      date: "Sep 2013 - Jul 2018",
      organization: "Fayoum University",
    }
  # - {
  #     name: Higher Secondary Certificat,
  #     date: "2000",
  #     organization: "Cardiff School",
  #   }
  # - {
  #     name: Secondary School Certificate,
  #     date: "1998",
  #     organization: "Cardiff School",
  #   }

#-------------------------------
# Services Section

services-title: Commercial Projects
services:
  - {
      name: Pricing,
      icon: ti-palette,
      description: "Working with insurance policy data and market data to build predictive models based on pricing and non-pricing factors.",
      active: true, # Add true to select section
    }
  - {
      name: Customer and Marketing,
      icon: ti-vector,
      description: "Worked in the telecom industry on multiple machine learning and analytics projects ranging from customer targeting, offering matrices, A/B tests, Life time value, recharge localisation and cross-sell.",
      active: true, # Add true to select section
    }
  - {
      name: Other Projects,
      icon: ti-panel,
      description: "Automated bid application for a startup using scraping and natural language processing. Delivered real-time moitoring dashboard for companies social media market share.",
      active: True, #Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Forum
contact-email: randaadelnaguib@gmail.com

